### ISSUE TITLE
register with npm?

### ISSUE THREAD

**Issue by rjrbt** [seandesmond/angular-payment#13]
We've moved away from bower and now use npm exclusively. Its easy enough to specifically call this git repo in our `package.json` but it would be super great if it was officially registered so versioning was easier.

npm?

**Comment by igalgh** [comment]
I do realize this is an old issue, yet I'd like to +1 that. We use Meteor which does not work with bower. As such, we have to copy the js into our project, which is fact from ideal. 

FYI publishing the package on npm should be a [few simple steps](https://docs.npmjs.com/getting-started/publishing-npm-packages). 
So.. why not?
